# Generated by Django 3.2.7 on 2021-09-28 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('empID', models.AutoField(db_column='emp_ID', primary_key=True, serialize=False)),
                ('empName', models.CharField(db_column='emp_Name', max_length=50)),
                ('empEmail', models.EmailField(db_column='emp_Email', max_length=200)),
                ('password', models.CharField(db_column='password', max_length=50)),
                ('empAddress', models.CharField(db_column='emp_Address', max_length=255)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
